package net.samagames.tools.teamspeak;

/**
 * Created by Rigner for project SamaGamesAPI.
 */
public enum ChannelProperty
{
    CHANNEL_CODEC,
    CHANNEL_CODEC_IS_UNENCRYPTED,
    CHANNEL_CODEC_QUALITY,
    CHANNEL_DESCRIPTION,
    CHANNEL_FLAG_DEFAULT,
    CHANNEL_FLAG_MAXCLIENTS_UNLIMITED,
    CHANNEL_FLAG_MAXFAMILYCLIENTS_INHERITED,
    CHANNEL_FLAG_MAXFAMILYCLIENTS_UNLIMITED,
    CHANNEL_FLAG_PERMANENT,
    CHANNEL_FLAG_SEMI_PERMANENT,
    CHANNEL_FLAG_TEMPORARY,
    CHANNEL_ICON_ID,
    CHANNEL_MAXCLIENTS,
    CHANNEL_MAXFAMILYCLIENTS,
    CHANNEL_NAME,
    CHANNEL_NAME_PHONETIC,
    CHANNEL_NEEDED_TALK_POWER,
    CHANNEL_ORDER,
    CHANNEL_PASSWORD,
    CHANNEL_TOPIC,
    CPID
}
